---
name: Puppet

on:
  workflow_call:
    inputs:
      rubocop:
        description: Whether to run Rubocop
        default: true
        required: false
        type: boolean
      timeout_minutes:
        description: The maximum time (in minutes) for a job to take.
        default: 45
        required: false
        type: number
      working-directory:
        description: The working directory where all jobs should be executed. Used for modules in subdirectories like a monorepo or a control repository.
        default: '.'
        required: false
        type: string
      cache-version:
        description: The cache version to pass to setup-ruby
        default: '0'
        required: false
        type: string
      additional_packages:
        description: String of additional packages that should be installed
        default: ''
        required: false
        type: string
      unit_runs_on:
        description: the runner group used for unit jobs run on
        default: ubuntu-24.04
        required: false
        type: string

jobs:
  setup_matrix:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    name: Static validations
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    outputs:
      puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
      github_action_test_matrix: ${{ steps.get-outputs.outputs.github_action_test_matrix }}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_GEM_VERSION: ">= 7.0"
      OPENVOX_GEM_VERSION: ">= 7.0"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: install additional packages
        if: ${{ inputs.additional_packages != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.additional_packages }}
      - name: Setup ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: ${{ inputs.cache-version }}
          working-directory: ${{ inputs.working-directory }}
      - name: Display Ruby environment
        run: bundle env
      - name: Run static validations
        run: bundle exec rake validate lint check
      - name: Run rake rubocop
        run: bundle exec rake rubocop
        if: ${{ inputs.rubocop }}
      - name: Setup Test Matrix
        id: get-outputs
        run: bundle exec metadata2gha

  unit:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    needs: setup_matrix
    runs-on: ${{ inputs.unit_runs_on }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_unit_test_matrix)}}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
      OPENVOX_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
    name: ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: install additional packages
        if: ${{ inputs.additional_packages != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.additional_packages }}
      - name: Setup ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: ${{ inputs.cache-version }}
          working-directory: ${{ inputs.working-directory }}
      - name: Display Ruby environment
        run: bundle env
      - name: Run tests
        run: bundle exec rake parallel_spec

  tests:
    if: always()
    needs: unit
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
