---

name: Create Git tag

on:
  workflow_call:
    inputs:
      allowed_owner:
        description: 'Only allow this owner'
        required: true
        type: string
      working-directory:
        description: 'The working directory where all jobs should be executed. Used for modules in subdirectories like a monorepo or a control repository.'
        default: '.'
        required: false
        type: string
      base-branch:
        description: 'The branch that will be used as the origin for the release.'
        required: false
        default: ''
        type: string
      git_name:
        description: 'name for the git committer and author'
        required: false
        default: 'Release Automation'
        type: string
      git_email:
        description: 'email for the git committer and author'
        required: false
        default: "${{ github.repository_owner }}@users.noreply.github.com"
        type: string
    secrets:
      ssh_private_key:
        description: 'private key used to sign commits & authenticate to GitHub'
        required: true

env:
  BUNDLE_WITHOUT: development:test:system_tests
  BUNDLE_WITH: release
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  # https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables
  GIT_AUTHOR_NAME: "${{ inputs.git_name }}"
  GIT_AUTHOR_EMAIL: "${{ inputs.git_email }}"
  GIT_COMMITTER_NAME: "${{ inputs.git_name }}"
  GIT_COMMITTER_EMAIL: "${{ inputs.git_email }}"

jobs:
  prepare_release:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    name: 'Prepare Release'
    runs-on: ubuntu-24.04
    if: github.repository_owner == inputs.allowed_owner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.base-branch }}
          ssh-key: "${{ secrets.ssh_private_key }}"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
          working-directory: ${{ inputs.working-directory }}
      - name: Display Ruby environment
        run: bundle env
      - name: Add SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.ssh_private_key }}" > ~/.ssh/github_actions
            chmod 600 ~/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add ~/.ssh/github_actions
      - name: set git user & email & commit signing
        run: |
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/github_actions
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true
      - name: create git tag + push it
        run: bundle exec rake release:tag_and_push
